### ISSUE TITLE
Division by square root of number of folds

### ISSUE THREAD

**Issue by fraspass** [marcusGH/edain_paper#1]
https://github.com/marcusGH/edain_paper/blob/bf144aa51eef433740c8044bfa9e04f9e94483a9/src/lib/plotting.py#L114

Add possibility to divide the estimate of the standard deviation by the square root of the number of folds for more appropriate confidence intervals. 

Proposed solution, replace `np.std(vals) * 1.96` with `np.std(vals) * 1.96 / np.sqrt(len(vals))`

**Comment by marcusGH** [comment]
Implemented in [this commit](https://github.com/marcusGH/edain_paper/commit/afcb6fc8c98de8b845a47de05568500f4683b4bb)
